apiVersion: v1
kind: Service
metadata:
  name: nodejs-k8s-service
spec:
  selector:
    app: nodejs-k8s-service
  ports:
  - protocol: "TCP"
    port: 9000
    nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-k8s-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-k8s-service
  template:
    metadata:
      labels:
        app: nodejs-k8s-service
    spec: # pod spec                  
      containers:
      - name: nodejs-k8s-service
        image: silvestri/nodejs-k8s:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
